<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'id' => 1,
                'user_id' => 7,
                'deleted_at' => NULL,
                'company_id' => 5,
                'company_model_id' => 5,
                'year' => 2019,
                'parts_type' => 'new',
                'form_image' => NULL,
                'structure_number' => NULL,
                'payment_type' => 'cash',
                'status' => 'new',
                'completed_status' => NULL,
                'created_at' => '2019-06-02 00:00:00',
                'updated_at' => '2019-06-02 00:00:00',
                'city_id' => 1,
                'winner_reply_id' => 4,
                'app_percentage' => 25.0,
                'delivery_value' => 10.0,
                'total' => 485.0,
                'supplier_percent' => 450.0,
            ),
            1 =>
                array (
                    'id' => 2,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            2 =>
                array (
                    'id' => 3,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            3 =>
                array (
                    'id' => 4,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            4 =>
                array (
                    'id' => 5,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            5 =>
                array (
                    'id' =>6,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            6 =>
                array (
                    'id' => 7,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            7 =>
                array (
                    'id' => 8,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            8 =>
                array (
                    'id' => 9,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
            9 =>
                array (
                    'id' => 10,
                    'user_id' => 7,
                    'deleted_at' => NULL,
                    'company_id' => 5,
                    'company_model_id' => 5,
                    'year' => 2019,
                    'parts_type' => 'new',
                    'form_image' => NULL,
                    'structure_number' => NULL,
                    'payment_type' => 'cash',
                    'status' => 'new',
                    'completed_status' => NULL,
                    'created_at' => '2019-06-02 00:00:00',
                    'updated_at' => '2019-06-02 00:00:00',
                    'city_id' => 1,
                    'winner_reply_id' => 4,
                    'app_percentage' => 25.0,
                    'delivery_value' => 10.0,
                    'total' => 485.0,
                    'supplier_percent' => 450.0,
                ),
        ));
        
        
    }
}
